/**
 * Auto-generated type for FetchVenueScheduleResponse
 * Generated by ParksAPI type detection
 *
 * Based on the following HTTP requests:
 *   - GET /api/venues/13825/hours
 */

export type FetchVenueScheduleResponse = {
  CloseTimeString: string;
  CloseTimeUnix: number;
  Date: string;
  EarlyEntryString: string;
  EarlyEntryUnix: number;
  Holiday: boolean;
  IsShowScheduled: boolean;
  OpenTimeString: string;
  OpenTimeUnix: number;
  SpecialEntryUnix: number;
}[];
