/**
 * Auto-generated type for FetchWaitTimesResponse
 * Generated by ParksAPI type detection
 *
 * Based on the following HTTP requests:
 *   - GET /ush/wait-time/wait-time-attraction-list.json
 */

export type FetchWaitTimesResponse = {
  category: string;
  land_id: string;
  name: string;
  queues: {
    alternate_ids: {
      system_id: string;
      system_name: string;
    }[];
    display_wait_time?: number;
    last_tram_time?: string;
    queue_id: string;
    queue_type: string;
    recurring?: boolean;
    status: string;
  }[];
  resort_area_code: string;
  show_externally: boolean;
  venue_id: string;
  wait_time_attraction_id: string;
}[];
