/**
 * Auto-generated type for FetchParksResponse
 * Generated by ParksAPI type detection
 *
 * Based on the following HTTP requests:
 *   - GET /api/venues?city=hollywood
 */

export interface FetchParksResponse {
  NextPage: string;
  Pages: number;
  PreviousPage: string;
  Results: {
    AdmissionRequired: boolean;
    ContainedLands: {
      ContainingVenueId: number;
      ExternalIds: {
        ContentId: string;
        Tridion13: string;
      };
      GpsBoundary: {
        Latitude: number;
        Longitude: number;
      }[];
      Id: number;
      Latitude: number;
      Longitude: number;
      MblDisplayName: string;
    }[];
    DetailImages: any[];
    ExternalIds: {
      ContentId: string;
      ParkHoursDb: string;
      PlaceId: string;
      Tridion13: string;
    };
    GpsBoundary: {
      Latitude: number;
      Longitude: number;
    }[];
    GpsBoundaryCircle: {
      Latitude: number;
      Longitude: number;
      RadiusInMeters: number;
    };
    Hours: {
      CloseTimeString: string;
      CloseTimeUnix: number;
      Date: string;
      EarlyEntryString?: string;
      EarlyEntryUnix: number;
      Holiday: boolean;
      IsShowScheduled: boolean;
      OpenTimeString: string;
      OpenTimeUnix: number;
      SpecialEntryUnix: number;
    }[];
    Id: number;
    Latitude: number;
    Longitude: number;
    MblDisplayName: string;
    StreetAddress: {
      AddressLine1: string;
      City: string;
      State: string;
      ZipCode: string;
    };
    Url: string;
    VenueType: string;
  }[];
  TotalCount: number;
}
