/**
 * Auto-generated type for FetchPOIResponse
 * Generated by ParksAPI type detection
 *
 * Based on the following HTTP requests:
 *   - GET /api/pointsofinterest?city=orlando
 */

export interface FetchPOIResponse {
  Atms: {
    Category: string;
    DetailImages: any[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      Tridion13: string;
    };
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    Longitude: number;
    MblDisplayName: string;
    OfferIds: any[];
    Prices: any[];
    Tags: string[];
    ThumbnailImage: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  ChargingStations: any[];
  DiningLocations: {
    Category: string;
    DailyHours: {
      Friday: {
        CloseTime?: string;
        OpenTime?: string;
      };
      Monday: {
        CloseTime?: string;
        OpenTime?: string;
      };
      Saturday: {
        CloseTime?: string;
        OpenTime?: string;
      };
      Sunday: {
        CloseTime?: string;
        OpenTime?: string;
      };
      Thursday: {
        CloseTime?: string;
        OpenTime?: string;
      };
      Tuesday: {
        CloseTime?: string;
        OpenTime?: string;
      };
      Wednesday: {
        CloseTime?: string;
        OpenTime?: string;
      };
    };
    DetailImages: string[];
    DietaryOptions?: string[];
    DiningMenusLinks: (any | {
      MenuLink: string;
      MenuText: string;
    })[];
    DiningPlanAccepted: boolean;
    DiningServices?: string[];
    DiningTypes: string[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      MFOIdentifier?: string;
      PlaceId?: string;
      Tridion13: string;
    };
    GeneralCloseTime?: string;
    GeneralOpenTime?: string;
    GeoFences: (any | {
      Latitude: number;
      Longitude: number;
      Radius: number;
      Type: string;
    })[];
    HasCocaColaFreestyleMachine: boolean;
    HasHealthyOptions: boolean;
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage?: string;
    Longitude: number;
    MblDisplayName: string;
    MblLongDescription?: string;
    MblShortDescription?: string;
    MFDOOptions?: string[];
    OfferIds: any[];
    PhoneNumber?: string;
    Prices: any[];
    QuickServeParticipant: boolean;
    ReservationsSuggested: boolean;
    ReservationUrl?: string;
    SiteUrl?: string;
    SocialSharingText?: string;
    SupplementalTimingDetails?: string;
    Tags: (string | any)[];
    ThumbnailImage?: string;
    Tier?: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  Events: {
    Activities: any[];
    Category: string;
    Dates: (any | {
      StartDate: string;
      StartDateUnix: number;
    })[];
    DetailImages: string[];
    DisplayInEventList: boolean;
    EventSeriesIds: (number | any)[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      SharePoint?: string;
      Tridion13: string;
    };
    ExternalLinks: any[];
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    Location?: string;
    Longitude: number;
    MblDisplayName: string;
    MblShortDescription: string;
    OfferIds: any[];
    Prices: any[];
    RequiresAnnualPass: boolean;
    RequiresSeparateTicket: boolean;
    Tags: any[];
    ThumbnailImage: string;
    TicketedEventDetails?: string;
    VenueId: number;
    VirtualLine: boolean;
    WaitTime: number;
  }[];
  FamilyServices: any[];
  FirstAidStations: {
    Category: string;
    DetailImages: any[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      Tridion13: string;
    };
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    Longitude: number;
    MblDisplayName: string;
    OfferIds: any[];
    Prices: any[];
    Tags: string[];
    ThumbnailImage: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  Games: {
    Category: string;
    CharacterAsset: string;
    DetailImages: string[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      Tridion13: string;
    };
    Id: number;
    Images: (any | {
      ImageType: string;
      Url: string;
    })[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    Longitude: number;
    MblDisplayName: string;
    MblLongDescription: string;
    MblShortDescription: string;
    OfferIds: any[];
    Prices: any[];
    PrimaryColorLighter: string;
    PrimaryColorVariant: string;
    Tags: any[];
    Type: string;
    UnAuthenticatedDetail: string;
    UnAuthenticatedHeader: string;
    UniversalPlayHeaderColor: string;
    UniversalPlayURL: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  GeneralLocations: any[];
  GuestServices: {
    Category: string;
    DetailImages: any[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      Tridion13: string;
    };
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    Longitude: number;
    MblDisplayName: string;
    OfferIds: any[];
    Prices: any[];
    Tags: string[];
    ThumbnailImage: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  Hotels: {
    BenefitsInfo: {
      BenefitsCategory: string;
      Text: string;
      Title: string;
    }[];
    Category: string;
    DetailImages: string[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      Tridion13: string;
    };
    HotelPerks: string[];
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    Longitude: number;
    MblDisplayName: string;
    MblLongDescription?: string;
    MblShortDescription?: string;
    OfferIds: any[];
    Prices: any[];
    ReservationCopy?: string;
    ReservationsPhoneNumber: string;
    SiteUrl?: string;
    SocialSharingText?: string;
    Tags: string[];
    ThumbnailImage: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  Lands: any[];
  Lockers: {
    Category: string;
    DetailImages: string[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      Tridion13: string;
    };
    Id: number;
    Images: any[];
    IsFree: boolean;
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    LockerPrices: any[];
    LockerSizes: (any | {
      HeightInInches: number;
      LengthInInches: number;
      WidthInInches: number;
    })[];
    Longitude: number;
    MblDisplayName: string;
    MblShortDescription: string;
    OfferIds: any[];
    Prices: any[];
    Tags: any[];
    ThumbnailImage: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  LostAndFoundStations: {
    Category: string;
    DetailImages: any[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      Tridion13: string;
    };
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    Longitude: number;
    MblDisplayName: string;
    OfferIds: any[];
    Prices: any[];
    Tags: string[];
    ThumbnailImage: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  NightlifeLocations: {
    Category: string;
    DailyHours: {
      Friday: {
        CloseTime: string;
        OpenTime: string;
      };
      Monday: {
        CloseTime: string;
        OpenTime: string;
      };
      Saturday: {
        CloseTime: string;
        OpenTime: string;
      };
      Sunday: {
        CloseTime: string;
        OpenTime: string;
      };
      Thursday: {
        CloseTime: string;
        OpenTime: string;
      };
      Tuesday: {
        CloseTime: string;
        OpenTime: string;
      };
      Wednesday: {
        CloseTime: string;
        OpenTime: string;
      };
    };
    DetailImages: string[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      PlaceId?: string;
      Tridion13: string;
    };
    GeneralCloseTime?: string;
    GeneralOpenTime?: string;
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    Longitude: number;
    MblDisplayName: string;
    MblLongDescription: string;
    MinPrice?: number;
    OfferIds: any[];
    PartyPassAccepted?: boolean;
    Prices: any[];
    SiteUrl?: string;
    SocialSharingText?: string;
    Tags: (string | any)[];
    ThumbnailImage: string;
    Tier?: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  Parades: any[];
  PhoneCardDispensers: any[];
  Rentals: {
    Category: string;
    DetailImages: string[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      Tridion13: string;
    };
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    Longitude: number;
    MblDisplayName: string;
    MblLongDescription: string;
    OfferIds: any[];
    Prices: any[];
    RentalTypes: string[];
    Tags: any[];
    TermsAndConditions: string;
    ThumbnailImage: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  Restrooms: {
    Category: string;
    DetailImages: any[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      Tridion13: string;
    };
    Id: number;
    Images: any[];
    IsFamilyFriendly: boolean;
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    Longitude: number;
    MblDisplayName: string;
    OfferIds: any[];
    Prices: any[];
    Tags: string[];
    ThumbnailImage: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  Rides: {
    AccessibilityOptions: string[];
    AdaDescription?: string;
    Category: string;
    DetailImages: (string | any)[];
    EventSeriesOnly: boolean;
    ExpressPassAccepted: boolean;
    ExternalIds: {
      ContentId: string;
      PlaceId?: string;
      SharePoint?: string;
      Tridion13: string;
    };
    FunFact?: string;
    HasChildSwap: boolean;
    HasNominalFee: boolean;
    HasSingleRiderLine: boolean;
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage?: string;
    Longitude: number;
    MaxHeightInInches?: number;
    MblDisplayName: string;
    MblLongDescription?: string;
    MblShortDescription?: string;
    MinHeightInInches?: number;
    OfferIds: any[];
    OpensAt?: string;
    P406LocationId?: string;
    PeakHeightInFeet?: number;
    Prices: any[];
    QueueImage?: string;
    Recurring?: boolean;
    RideTypes?: string[];
    SiteUrl?: string;
    SocialSharingText?: string;
    Tags: (string | any)[];
    ThumbnailImage?: string;
    Tier?: string;
    TopSpeedInMph?: number;
    VenueId: number;
    VirtualLine: boolean;
    WaitTime: number;
  }[];
  ServiceAnimalRestAreas: {
    Category: string;
    DetailImages: (any | string)[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      Tridion13: string;
    };
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    Longitude: number;
    MblDisplayName: string;
    MblShortDescription?: string;
    OfferIds: any[];
    Prices: any[];
    Tags: (any | string)[];
    ThumbnailImage: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  Shops: {
    Category: string;
    DetailImages: (string | any)[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      PlaceId?: string;
      Tridion13: string;
    };
    HasPackagePickup: boolean;
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage?: string;
    Longitude: number;
    MblDisplayName: string;
    MblShortDescription: string;
    OfferIds: any[];
    Prices: any[];
    SellsExpressPass: boolean;
    ShopTypes?: string[];
    SiteUrl?: string;
    SocialSharingText?: string;
    Tags: (string | any)[];
    ThumbnailImage?: string;
    Tier?: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
  Shows: {
    AccessibilityOptions: (string | any)[];
    Category: string;
    ContinuousUntilParkClose: boolean;
    DetailImages: (string | any)[];
    EndDateTimes: (any | string)[];
    EndTimes: (any | string)[];
    EventSeriesOnly: boolean;
    ExpressPassAccepted: boolean;
    ExternalIds: {
      ContentId: string;
      PlaceId: string;
      SharePoint?: string;
      Tridion13: string;
    };
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage?: string;
    Longitude: number;
    MblDisplayName: string;
    MblLongDescription?: string;
    MblShortDescription?: string;
    OfferIds: any[];
    OpensAt?: string;
    Prices: any[];
    ShowTypes: string[];
    SiteUrl?: string;
    SocialSharingText?: string;
    StartDateTimes: (string | any)[];
    StartTimes: (string | any)[];
    Tags: (string | any)[];
    ThumbnailImage?: string;
    Tier: string;
    VenueId: number;
    VirtualLine: boolean;
    WaitTime: number;
  }[];
  SmokingAreas: {
    Category: string;
    DetailImages: any[];
    EventSeriesOnly: boolean;
    ExternalIds: {
      ContentId: string;
      Tridion13: string;
    };
    Id: number;
    Images: any[];
    IsRoutable: boolean;
    LandId: number;
    Latitude: number;
    ListImage: string;
    Longitude: number;
    MblDisplayName: string;
    OfferIds: any[];
    Prices: any[];
    Tags: any[];
    ThumbnailImage: string;
    VenueId: number;
    VirtualLine: boolean;
  }[];
}
