/**
 * Auto-generated type for FetchAPIKeyResponse
 * Generated by ParksAPI type detection
 *
 * Based on the following HTTP requests:
 *   - POST /api?city=orlando
 */

export interface FetchAPIKeyResponse {
  Token: string;
  BaseUrl: string;
  ServicesBaseUrl: string;
  MinimumRequiredVersionAndroid: string;
  MinimumRequiredVersioniOS: string;
  TokenExpirationString: string;
  TokenExpirationUnix: number;
  ExPassNotificationInvervalInMin: number;
  OrlandoActiveMapTileSetId: number;
  OrlandoActiveMapTileSetBaseColor: string;
  OrlandoMapTileDownloadMaxZoomLimit: number;
  OrlandoGeoFence: {
    Latitude: number;
    Longitude: number;
  }[];
  OrlandoGeoFenceCircle: {
    RadiusInMeters: number;
    Latitude: number;
    Longitude: number;
  };
  EpicGeoFence: {
    Latitude: number;
    Longitude: number;
  }[];
  EpicGeoFenceCircle: {
    RadiusInMeters: number;
    Latitude: number;
    Longitude: number;
  };
  OrlandoExpressPassUrl: string;
  WaitTimeUpdateIntervalInSec: number;
  EventSeriesUpdateIntervalInSec: number;
  ShowTimeUpdateIntervalInSec: number;
  VenueHoursUpdateIntervalInSec: number;
  OrlandoFeaturedPointsOfInterest: any[];
  OrlandoFeaturedList: number[];
  GuestServicesPhoneNumber: string;
  GuestServicesEmailAddress: string;
  InParkWifiNetwork: string;
  RiderGuidePdfUrl: string;
  TicketWebstoreUrl: string;
  TicketHHNWebstoreUrl: string;
  GuestServicesDescription: string;
  GuestServicesDisplayEmail: string;
  GuestServicesTwitterUrl: string;
  GuestServicesDefaultShareText: string;
  EnableMFO: boolean;
  MFORequiredVersion: string;
  USH_ActiveMapTileSetId: number;
  USH_ActiveMapTileSetBaseColor: string;
  USHMapTileDownloadMaxZoomLimit: number;
  USH_WaitTimeUpdateIntervalInSec: number;
  USH_ShowTimeUpdateIntervalInSec: number;
  USH_VenueHoursUpdateIntervalInSec: number;
  USH_ExpressPassUrl: string;
  USH_FeaturedPointsOfInterest: number[];
  USH_FeaturedList: number[];
  USH_FeaturedOffers: any[];
  USH_GuestServicesPhoneNumber: string;
  USH_GuestServicesEmailAddress: string;
  USH_InParkWifiNetwork: string;
  USH_RiderGuidePdfUrl: string;
  USH_TicketWebstoreUrl: string;
  USH_TicketHHNWebstoreUrl: string;
  USH_GuestServicesDescription: string;
  USH_GuestServicesDisplayEmail: string;
  USH_GuestServicesTwitterUrl: string;
  USH_GuestServicesDefaultShareText: string;
  USH_FaqPageUrl: string;
  USJ_ActiveMapTileSetId: number;
  USJ_ActiveMapTileSetBaseColor: string;
  USJMapTileDownloadMaxZoomLimit: number;
  USJ_WaitTimeUpdateIntervalInSec: number;
  USJ_ShowTimeUpdateIntervalInSec: number;
  USJ_VenueHoursUpdateIntervalInSec: number;
  USJ_ExpressPassUrl: string;
  USJ_FeaturedPointsOfInterest: any[];
  USJ_FeaturedList: any[];
  USJ_FeaturedOffers: any[];
  USJ_GuestServicesEmailAddress: string;
  USJ_RiderGuidePdfUrl: string;
  USJ_TicketWebstoreUrl: string;
  USJ_TicketHHNWebstoreUrl: string;
  USJ_GuestServicesDescription: string;
  USJ_GuestServicesDisplayEmail: string;
  USJ_GuestServicesTwitterUrl: string;
  USJ_GuestServicesDefaultShareText: string;
  USJ_FaqPageUrl: string;
  MapTileSets: {
    Identifier: number;
    Type: string;
    RotationDegrees: number;
    ZoomLevelMin: number;
    ZoomLevelMax: number;
    ResortLevelBreakout: number;
    ParkLevelBreakout: number;
    BackgroundColor: string;
    CameraBounds: {
      LatitudeMin: number;
      LatitudeMax: number;
      LongitudeMin: number;
      LongitudeMax: number;
    };
  }[];
  DefaultEventsToEventSeries: boolean;
  CurrentCommerceVersionNumber: string;
  ParkNotificationRefreshInterval: string;
  GuestFeedback: {
    FeedbackTypes: any[];
  };
  CCPAUrl: string;
  DateBasedRestaurantHours: boolean;
  GPSLatLongIntervalInSec: number;
  LatLongTransFreq: number;
  QueuePollingIntervalInSec: number;
  MDVPSalesCatalogId: number;
  MDVPEnableGSS: boolean;
  VLReservationAllowTimeOverlap: boolean;
  InParkEventSeries: number[];
  OutOfParkEventSeries: number[];
  MapFilters: {
    Name: string;
    Type: string;
  }[];
}
