/**
 * Auto-generated type for FetchWaitTimesResponse
 * Generated by ParksAPI type detection
 *
 * Based on the following HTTP requests:
 *   - 2025-10-05T07:25:27.413Z: GET /uor/wait-time/wait-time-attraction-list.json
 */

export type FetchWaitTimesResponse = {
  wait_time_attraction_id: string;
  resort_area_code: string;
  venue_id: string;
  land_id: string;
  name: string;
  category: string;
  has_single_rider: boolean;
  show_externally: boolean;
  modified_at: string;
  is_aap: boolean;
  queues: {
    queue_id: string;
    queue_type: string;
    status: string;
    opens_at?: string;
    display_wait_time: number;
    alternate_ids: ({
      system_name: string;
      system_id: string;
    } | any)[];
    closes_at?: string;
  }[];
}[];
