/**
 * Auto-generated type for FetchParksResponse
 * Generated by ParksAPI type detection
 *
 * Based on the following HTTP requests:
 *   - 2025-10-05T07:25:26.895Z: GET /api/venues?city=orlando
 */

export interface FetchParksResponse {
  TotalCount: number;
  Pages: number;
  PreviousPage: string;
  NextPage: string;
  Results: {
    MblDisplayName: string;
    ContainedLands: {
      MblDisplayName: string;
      ContainingVenueId: number;
      Longitude: number;
      Latitude: number;
      ExternalIds: {
        Tridion13: string;
        ContentId: string;
        PlaceId?: string;
      };
      Id: number;
    }[];
    StreetAddress: {
      AddressLine1: string;
      City: string;
      State: string;
      ZipCode: string;
    };
    GpsBoundary?: {
      Latitude: number;
      Longitude: number;
    }[];
    GpsBoundaryCircle?: {
      RadiusInMeters: number;
      Latitude: number;
      Longitude: number;
    };
    Hours: (any | {
      Date: string;
      OpenTimeString?: string;
      CloseTimeString?: string;
      OpenTimeUnix: number;
      CloseTimeUnix: number;
      EarlyEntryUnix: number;
      VenueStatus?: string;
      SpecialEntryUnix: number;
      Holiday: boolean;
      IsShowScheduled: boolean;
      EarlyEntryString?: string;
    })[];
    AdmissionRequired: boolean;
    DetailImages: any[];
    Longitude: number;
    Latitude: number;
    Color?: string;
    VenueType: string;
    ExternalIds: {
      ParkHoursDb?: string;
      Tridion13: string;
      ParkHoursDbEarly?: string;
      ContentId: string;
      PlaceId: string;
    };
    Url: string;
    Id: number;
    PhoneNumber?: string;
    PhoneNumberCopy?: string;
  }[];
}
