/**
 * Auto-generated type for FetchPOIResponse
 * Generated by ParksAPI type detection
 *
 * Based on the following HTTP requests:
 *   - GET /api/pointsofinterest?city=orlando
 */

export interface FetchPOIResponse {
  Atms: {
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    Longitude: number;
    Latitude: number;
    DetailImages: any[];
    ListImage: string;
    ThumbnailImage: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: string[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
    };
    Id: number;
  }[];
  ChargingStations: any[];
  DiningLocations: {
    DiningServices?: string[];
    DiningTypes: string[];
    QuickServeParticipant: boolean;
    DiningPlanAccepted: boolean;
    HasHealthyOptions: boolean;
    PhoneNumber?: string;
    GeneralOpenTime?: string;
    GeneralCloseTime?: string;
    SiteUrl?: string;
    ReservationUrl?: string;
    SocialSharingText?: string;
    DailyHours: {
      Sunday: {
        OpenTime?: string;
        CloseTime?: string;
      };
      Monday: {
        OpenTime?: string;
        CloseTime?: string;
      };
      Tuesday: {
        OpenTime?: string;
        CloseTime?: string;
      };
      Wednesday: {
        OpenTime?: string;
        CloseTime?: string;
      };
      Thursday: {
        OpenTime?: string;
        CloseTime?: string;
      };
      Friday: {
        OpenTime?: string;
        CloseTime?: string;
      };
      Saturday: {
        OpenTime?: string;
        CloseTime?: string;
      };
    };
    ReservationsSuggested: boolean;
    HasCocaColaFreestyleMachine: boolean;
    DiningMenusLinks: (any | {
      MenuText: string;
      MenuLink: string;
    })[];
    GeoFences: (any | {
      Type: string;
      Radius: number;
      Latitude: number;
      Longitude: number;
    })[];
    MFDOOptions?: string[];
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    MblShortDescription?: string;
    Longitude: number;
    Latitude: number;
    DetailImages: string[];
    ListImage?: string;
    ThumbnailImage?: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: (string | any)[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    Tier?: string;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
      MFOIdentifier?: string;
      PlaceId?: string;
    };
    Id: number;
    DietaryOptions?: string[];
    SupplementalTimingDetails?: string;
    MblLongDescription?: string;
  }[];
  Events: {
    Dates: (any | {
      StartDate: string;
      StartDateUnix: number;
    })[];
    RequiresAnnualPass: boolean;
    RequiresSeparateTicket: boolean;
    Location?: string;
    Activities: any[];
    EventSeriesIds: (number | any)[];
    WaitTime: number;
    TicketedEventDetails?: string;
    DisplayInEventList: boolean;
    ExternalLinks: any[];
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    MblShortDescription: string;
    Longitude: number;
    Latitude: number;
    DetailImages: string[];
    ListImage: string;
    ThumbnailImage: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: any[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
      SharePoint?: string;
    };
    Id: number;
  }[];
  FamilyServices: any[];
  FirstAidStations: {
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    Longitude: number;
    Latitude: number;
    DetailImages: any[];
    ListImage: string;
    ThumbnailImage: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: string[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
    };
    Id: number;
  }[];
  GeneralLocations: any[];
  GuestServices: {
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    Longitude: number;
    Latitude: number;
    DetailImages: any[];
    ListImage: string;
    ThumbnailImage: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: string[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
    };
    Id: number;
  }[];
  Hotels: {
    HotelPerks: string[];
    ReservationsPhoneNumber: string;
    SiteUrl?: string;
    SocialSharingText?: string;
    BenefitsInfo: {
      Title: string;
      Text: string;
      BenefitsCategory: string;
    }[];
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    MblShortDescription?: string;
    Longitude: number;
    Latitude: number;
    DetailImages: string[];
    ListImage: string;
    ThumbnailImage: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: string[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
    };
    Id: number;
    MblLongDescription?: string;
    ReservationCopy?: string;
  }[];
  Lands: any[];
  Lockers: {
    IsFree: boolean;
    LockerSizes: (any | {
      HeightInInches: number;
      WidthInInches: number;
      LengthInInches: number;
    })[];
    LockerPrices: any[];
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    MblShortDescription: string;
    Longitude: number;
    Latitude: number;
    DetailImages: string[];
    ListImage: string;
    ThumbnailImage: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: any[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
    };
    Id: number;
  }[];
  LostAndFoundStations: {
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    Longitude: number;
    Latitude: number;
    DetailImages: any[];
    ListImage: string;
    ThumbnailImage: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: string[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
    };
    Id: number;
  }[];
  NightlifeLocations: {
    GeneralOpenTime?: string;
    GeneralCloseTime?: string;
    PartyPassAccepted?: boolean;
    DailyHours: {
      Sunday: {
        OpenTime: string;
        CloseTime: string;
      };
      Monday: {
        OpenTime: string;
        CloseTime: string;
      };
      Tuesday: {
        OpenTime: string;
        CloseTime: string;
      };
      Wednesday: {
        OpenTime: string;
        CloseTime: string;
      };
      Thursday: {
        OpenTime: string;
        CloseTime: string;
      };
      Friday: {
        OpenTime: string;
        CloseTime: string;
      };
      Saturday: {
        OpenTime: string;
        CloseTime: string;
      };
    };
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    MblLongDescription: string;
    Longitude: number;
    Latitude: number;
    DetailImages: string[];
    ListImage: string;
    ThumbnailImage: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: (string | any)[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
      PlaceId?: string;
    };
    Id: number;
    SiteUrl?: string;
    SocialSharingText?: string;
    Tier?: string;
    MinPrice?: number;
  }[];
  Parades: any[];
  PhoneCardDispensers: any[];
  Rentals: {
    RentalTypes: string[];
    TermsAndConditions: string;
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    MblLongDescription: string;
    Longitude: number;
    Latitude: number;
    DetailImages: string[];
    ListImage: string;
    ThumbnailImage: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: any[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
    };
    Id: number;
  }[];
  Restrooms: {
    IsFamilyFriendly: boolean;
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    Longitude: number;
    Latitude: number;
    DetailImages: any[];
    ListImage: string;
    ThumbnailImage: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: string[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
    };
    Id: number;
  }[];
  Rides: {
    MinHeightInInches?: number;
    ExpressPassAccepted: boolean;
    WaitTime: number;
    Recurring?: boolean;
    OpensAt?: string;
    HasChildSwap: boolean;
    PeakHeightInFeet?: number;
    TopSpeedInMph?: number;
    AccessibilityOptions: string[];
    HasSingleRiderLine: boolean;
    RideTypes?: string[];
    FunFact?: string;
    SiteUrl?: string;
    SocialSharingText?: string;
    HasNominalFee: boolean;
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    MblShortDescription?: string;
    Longitude: number;
    Latitude: number;
    DetailImages: (string | any)[];
    ListImage?: string;
    ThumbnailImage?: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: (string | any)[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    Tier?: string;
    ExternalIds: {
      Tridion13: string;
      SharePoint?: string;
      ContentId: string;
      PlaceId?: string;
    };
    Id: number;
    MaxHeightInInches?: number;
    QueueImage?: string;
    P406LocationId?: string;
    AdaDescription?: string;
    MblLongDescription?: string;
  }[];
  ServiceAnimalRestAreas: {
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    Longitude: number;
    Latitude: number;
    DetailImages: (any | string)[];
    ListImage: string;
    ThumbnailImage: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: (any | string)[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
    };
    Id: number;
    MblShortDescription?: string;
  }[];
  Shops: {
    SellsExpressPass: boolean;
    SiteUrl?: string;
    SocialSharingText?: string;
    HasPackagePickup: boolean;
    ShopTypes?: string[];
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    MblShortDescription: string;
    Longitude: number;
    Latitude: number;
    DetailImages: (string | any)[];
    ListImage?: string;
    ThumbnailImage?: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: (string | any)[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    Tier?: string;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
      PlaceId?: string;
    };
    Id: number;
  }[];
  Shows: {
    StartTimes: (string | any)[];
    StartDateTimes: (string | any)[];
    EndTimes: (any | string)[];
    EndDateTimes: (any | string)[];
    WaitTime: number;
    ExpressPassAccepted: boolean;
    ShowTypes: string[];
    AccessibilityOptions: (string | any)[];
    SiteUrl?: string;
    SocialSharingText?: string;
    ContinuousUntilParkClose: boolean;
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    MblLongDescription?: string;
    MblShortDescription?: string;
    Longitude: number;
    Latitude: number;
    DetailImages: (string | any)[];
    ListImage?: string;
    ThumbnailImage?: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: (string | any)[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    Tier: string;
    ExternalIds: {
      Tridion13: string;
      SharePoint?: string;
      ContentId: string;
      PlaceId: string;
    };
    Id: number;
    OpensAt?: string;
  }[];
  SmokingAreas: {
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    Longitude: number;
    Latitude: number;
    DetailImages: any[];
    ListImage: string;
    ThumbnailImage: string;
    Images: any[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: any[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
    };
    Id: number;
  }[];
  Games: {
    Type: string;
    UnAuthenticatedHeader: string;
    UnAuthenticatedDetail: string;
    PrimaryColorLighter: string;
    PrimaryColorVariant: string;
    CharacterAsset: string;
    Category: string;
    MblDisplayName: string;
    LandId: number;
    VenueId: number;
    MblLongDescription: string;
    MblShortDescription: string;
    Longitude: number;
    Latitude: number;
    DetailImages: string[];
    ListImage: string;
    Images: (any | {
      ImageType: string;
      Url: string;
    })[];
    IsRoutable: boolean;
    EventSeriesOnly: boolean;
    Tags: any[];
    OfferIds: any[];
    Prices: any[];
    VirtualLine: boolean;
    UniversalPlayURL: string;
    UniversalPlayHeaderColor: string;
    ExternalIds: {
      Tridion13: string;
      ContentId: string;
    };
    Id: number;
  }[];
}
