/**
 * Auto-generated type for FetchVenueScheduleResponse
 * Generated by ParksAPI type detection
 *
 * Based on the following HTTP requests:
 *   - GET /api/venues/10010/hours
 *   - GET /api/venues/10000/hours
 *   - GET /api/venues/24000/hours
 *   - GET /api/venues/13801/hours
 */

export type FetchVenueScheduleResponse = {
  Date: string;
  OpenTimeString?: string;
  CloseTimeString?: string;
  OpenTimeUnix: number;
  CloseTimeUnix: number;
  EarlyEntryUnix: number;
  VenueStatus: string;
  SpecialEntryUnix: number;
  Holiday: boolean;
  IsShowScheduled: boolean;
  EarlyEntryString?: string;
}[];
