/**
 * Auto-generated type for FetchVirtualQueueStatesResponse
 * Generated by ParksAPI type detection
 *
 * Based on the following HTTP requests:
 *   - GET /api/Queues
 */

export interface FetchVirtualQueueStatesResponse {
  TotalCount: number;
  Pages: number;
  PreviousPage: string;
  NextPage: string;
  Results: {
    Id: number;
    PlaceId?: string;
    Name: string;
    MaxAppointmentSize: number;
    AppointmentDuration: string;
    SessionTimeoutInSec: number;
    QueueEntityId: number;
    QueueEntityType: string;
    GracePeriodInMin?: number;
    IsEnabled: boolean;
    IsUnavailable: boolean;
    IsProfileAware: boolean;
  }[];
}
