window.esdocSearchIndex = [
  [
    "@themeparks/parksapi/lib/cache/cachebase.js~cachebase",
    "class/lib/cache/cacheBase.js~CacheBase.html",
    "<span>CacheBase</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/cache/cacheBase.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/cache/cachelevel.js~cachelevel",
    "class/lib/cache/cacheLevel.js~CacheLevel.html",
    "<span>CacheLevel</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/cache/cacheLevel.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/cache/cachememory.js~cachememory",
    "class/lib/cache/cacheMemory.js~CacheMemory.html",
    "<span>CacheMemory</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/cache/cacheMemory.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/configbase.js~configbase",
    "class/lib/configBase.js~ConfigBase.html",
    "<span>ConfigBase</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/configBase.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/database.js~database",
    "class/lib/parks/database.js~Database.html",
    "<span>Database</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/database.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/europa/europaparkdb.js~databaseeuropapark",
    "class/lib/parks/europa/europaparkdb.js~DatabaseEuropaPark.html",
    "<span>DatabaseEuropaPark</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/europa/europaparkdb.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/wdw/wdwdatabase.js~databasewdw",
    "class/lib/parks/wdw/wdwdatabase.js~DatabaseWDW.html",
    "<span>DatabaseWDW</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/wdw/wdwdatabase.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js~disneypark",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneyPark.html",
    "<span>DisneyPark</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/dlp/disneylandparis.js~disneylandparismagickingdom",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisMagicKingdom.html",
    "<span>DisneylandParisMagicKingdom</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/dlp/disneylandparis.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/dlp/disneylandparis.js~disneylandparispark",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisPark.html",
    "<span>DisneylandParisPark</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/dlp/disneylandparis.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/dlp/disneylandparis.js~disneylandpariswaltdisneystudios",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisWaltDisneyStudios.html",
    "<span>DisneylandParisWaltDisneyStudios</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/dlp/disneylandparis.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js~disneylandresortcaliforniaadventure",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneylandResortCaliforniaAdventure.html",
    "<span>DisneylandResortCaliforniaAdventure</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js~disneylandresortmagickingdom",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneylandResortMagicKingdom.html",
    "<span>DisneylandResortMagicKingdom</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/efteling/efteling.js~efteling",
    "class/lib/parks/efteling/efteling.js~Efteling.html",
    "<span>Efteling</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/efteling/efteling.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/entity.js~entity",
    "class/lib/parks/entity.js~Entity.html",
    "<span>Entity</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/entity.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/europa/europapark.js~europapark",
    "class/lib/parks/europa/europapark.js~EuropaPark.html",
    "<span>EuropaPark</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/europa/europapark.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/europa/europapark.js~europaparkbase",
    "class/lib/parks/europa/europapark.js~EuropaParkBase.html",
    "<span>EuropaParkBase</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/europa/europapark.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/http.js~http",
    "function/index.html#static-function-HTTP",
    "<span>HTTP</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/http.js</span>",
    "function"
  ],
  [
    "@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js~hongkongdisneylandpark",
    "class/lib/parks/wdw/waltdisneyworldbase.js~HongKongDisneylandPark.html",
    "<span>HongKongDisneylandPark</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/wdw/wdwdb.js~indexedwdwdb",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html",
    "<span>IndexedWDWDB</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/wdw/wdwdb.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/park.js~park",
    "class/lib/parks/park.js~Park.html",
    "<span>Park</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/park.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/resort.js~resort",
    "class/lib/parks/resort.js~Resort.html",
    "<span>Resort</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/resort.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/europa/europapark.js~rulantica",
    "class/lib/parks/europa/europapark.js~Rulantica.html",
    "<span>Rulantica</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/europa/europapark.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/cache/scopedcache.js~scopedcache",
    "class/lib/cache/scopedCache.js~ScopedCache.html",
    "<span>ScopedCache</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/cache/scopedCache.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/sieve.js~sieve",
    "function/index.html#static-function-Sieve",
    "<span>Sieve</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/sieve.js</span>",
    "function"
  ],
  [
    "@themeparks/parksapi/lib/parks/tdr/tokyodisneyresort.js~tokyodisneyresortpark",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark.html",
    "<span>TokyoDisneyResortPark</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/tdr/tokyodisneyresort.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/tdr/tokyodisneyresort.js~tokyodisneysea",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneySea.html",
    "<span>TokyoDisneySea</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/tdr/tokyodisneyresort.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/tdr/tokyodisneyresort.js~tokyodisneyland",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyland.html",
    "<span>TokyoDisneyland</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/tdr/tokyodisneyresort.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js~waltdisneyworldanimalkingdom",
    "class/lib/parks/wdw/waltdisneyworldbase.js~WaltDisneyWorldAnimalKingdom.html",
    "<span>WaltDisneyWorldAnimalKingdom</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js~waltdisneyworldepcot",
    "class/lib/parks/wdw/waltdisneyworldbase.js~WaltDisneyWorldEpcot.html",
    "<span>WaltDisneyWorldEpcot</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js~waltdisneyworldhollywoodstudios",
    "class/lib/parks/wdw/waltdisneyworldbase.js~WaltDisneyWorldHollywoodStudios.html",
    "<span>WaltDisneyWorldHollywoodStudios</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js~waltdisneyworldmagickingdom",
    "class/lib/parks/wdw/waltdisneyworldbase.js~WaltDisneyWorldMagicKingdom.html",
    "<span>WaltDisneyWorldMagicKingdom</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/wdw/waltdisneyworldbase.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/europa/europapark.js~yullbe",
    "class/lib/parks/europa/europapark.js~Yullbe.html",
    "<span>Yullbe</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/europa/europapark.js</span>",
    "class"
  ],
  [
    "@themeparks/parksapi/lib/parks/parktypes.js~attractiontype",
    "variable/index.html#static-variable-attractionType",
    "<span>attractionType</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/parkTypes.js</span>",
    "variable"
  ],
  [
    "@themeparks/parksapi/lib/parks/types.js~entitytype",
    "variable/index.html#static-variable-entityType",
    "<span>entityType</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/types.js</span>",
    "variable"
  ],
  [
    "@themeparks/parksapi/lib/parks/http.js~generaterandomandroiduseragent",
    "function/index.html#static-function-generateRandomAndroidUseragent",
    "<span>generateRandomAndroidUseragent</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/http.js</span>",
    "function"
  ],
  [
    "@themeparks/parksapi/lib/cache.js~getcache",
    "function/index.html#static-function-getCache",
    "<span>getCache</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/cache.js</span>",
    "function"
  ],
  [
    "@themeparks/parksapi/lib/parks/wdw/wdwdb.js~getentityid",
    "function/index.html#static-function-getEntityID",
    "<span>getEntityID</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/wdw/wdwdb.js</span>",
    "function"
  ],
  [
    "@themeparks/parksapi/lib/parks/tags.js~getvalidtagobject",
    "function/index.html#static-function-getValidTagObject",
    "<span>getValidTagObject</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/tags.js</span>",
    "function"
  ],
  [
    "@themeparks/parksapi/lib/parks/tags.js~issimpletagtype",
    "function/index.html#static-function-isSimpleTagType",
    "<span>isSimpleTagType</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/tags.js</span>",
    "function"
  ],
  [
    "@themeparks/parksapi/lib/parks/tags.js~isvalidtag",
    "function/index.html#static-function-isValidTag",
    "<span>isValidTag</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/tags.js</span>",
    "function"
  ],
  [
    "@themeparks/parksapi/lib/parks/tags.js~isvalidtagtype",
    "function/index.html#static-function-isValidTagType",
    "<span>isValidTagType</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/tags.js</span>",
    "function"
  ],
  [
    "@themeparks/parksapi/lib/configbase.js~parseconfig",
    "function/index.html#static-function-parseConfig",
    "<span>parseConfig</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/configBase.js</span>",
    "function"
  ],
  [
    "@themeparks/parksapi/lib/parks/parktypes.js~queuetype",
    "variable/index.html#static-variable-queueType",
    "<span>queueType</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/parkTypes.js</span>",
    "variable"
  ],
  [
    "@themeparks/parksapi/lib/parks/parktypes.js~returntimestate",
    "variable/index.html#static-variable-returnTimeState",
    "<span>returnTimeState</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/parkTypes.js</span>",
    "variable"
  ],
  [
    "@themeparks/parksapi/lib/reusepromises.js~reusepromise",
    "function/index.html#static-function-reusePromise",
    "<span>reusePromise</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/reusePromises.js</span>",
    "function"
  ],
  [
    "@themeparks/parksapi/lib/reusepromises.js~reusepromiseforever",
    "function/index.html#static-function-reusePromiseForever",
    "<span>reusePromiseForever</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/reusePromises.js</span>",
    "function"
  ],
  [
    "@themeparks/parksapi/lib/parks/parktypes.js~scheduletype",
    "variable/index.html#static-variable-scheduleType",
    "<span>scheduleType</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/parkTypes.js</span>",
    "variable"
  ],
  [
    "@themeparks/parksapi/lib/parks/parktypes.js~statustype",
    "variable/index.html#static-variable-statusType",
    "<span>statusType</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/parkTypes.js</span>",
    "variable"
  ],
  [
    "@themeparks/parksapi/lib/parks/parktypes.js~tagtype",
    "variable/index.html#static-variable-tagType",
    "<span>tagType</span> <span class=\"search-result-import-path\">@themeparks/parksapi/lib/parks/parkTypes.js</span>",
    "variable"
  ],
  [
    "lib/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "lib/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "lib/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "lib/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "lib/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "lib/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "lib/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "lib/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "lib/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "lib/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "lib/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "lib/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "lib/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "lib/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "lib/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "lib/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "lib/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "lib/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "lib/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "lib/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "lib/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "lib/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "lib/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "lib/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "lib/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "lib/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~String",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "lib/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "lib/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "lib/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "lib/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "lib/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "lib/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "lib/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "lib/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "lib/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "lib/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "lib/.external-ecmascript.js~null",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~string",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "lib/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "lib/cache.js",
    "file/lib/cache.js.html",
    "lib/cache.js",
    "file"
  ],
  [
    "lib/cache/cachebase.js",
    "file/lib/cache/cacheBase.js.html",
    "lib/cache/cacheBase.js",
    "file"
  ],
  [
    "lib/cache/cachebase.js~cachebase#_del",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-_del",
    "lib/cache/cacheBase.js~CacheBase#_del",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#_get",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-_get",
    "lib/cache/cacheBase.js~CacheBase#_get",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#_getkeys",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-_getKeys",
    "lib/cache/cacheBase.js~CacheBase#_getKeys",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#_set",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-_set",
    "lib/cache/cacheBase.js~CacheBase#_set",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#constructor",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-constructor-constructor",
    "lib/cache/cacheBase.js~CacheBase#constructor",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#failedcachewraps",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-member-failedCacheWraps",
    "lib/cache/cacheBase.js~CacheBase#failedCacheWraps",
    "member"
  ],
  [
    "lib/cache/cachebase.js~cachebase#get",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-get",
    "lib/cache/cacheBase.js~CacheBase#get",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#getkeys",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-getKeys",
    "lib/cache/cacheBase.js~CacheBase#getKeys",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#memcache",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-member-memCache",
    "lib/cache/cacheBase.js~CacheBase#memCache",
    "member"
  ],
  [
    "lib/cache/cachebase.js~cachebase#memorylayerenabled",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-member-memoryLayerEnabled",
    "lib/cache/cacheBase.js~CacheBase#memoryLayerEnabled",
    "member"
  ],
  [
    "lib/cache/cachebase.js~cachebase#pendingcachewraps",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-member-pendingCacheWraps",
    "lib/cache/cacheBase.js~CacheBase#pendingCacheWraps",
    "member"
  ],
  [
    "lib/cache/cachebase.js~cachebase#set",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-set",
    "lib/cache/cacheBase.js~CacheBase#set",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#wrap",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-wrap",
    "lib/cache/cacheBase.js~CacheBase#wrap",
    "method"
  ],
  [
    "lib/cache/cachelevel.js",
    "file/lib/cache/cacheLevel.js.html",
    "lib/cache/cacheLevel.js",
    "file"
  ],
  [
    "lib/cache/cachelevel.js~cachelevel#_del",
    "class/lib/cache/cacheLevel.js~CacheLevel.html#instance-method-_del",
    "lib/cache/cacheLevel.js~CacheLevel#_del",
    "method"
  ],
  [
    "lib/cache/cachelevel.js~cachelevel#_get",
    "class/lib/cache/cacheLevel.js~CacheLevel.html#instance-method-_get",
    "lib/cache/cacheLevel.js~CacheLevel#_get",
    "method"
  ],
  [
    "lib/cache/cachelevel.js~cachelevel#_getkeys",
    "class/lib/cache/cacheLevel.js~CacheLevel.html#instance-method-_getKeys",
    "lib/cache/cacheLevel.js~CacheLevel#_getKeys",
    "method"
  ],
  [
    "lib/cache/cachelevel.js~cachelevel#_set",
    "class/lib/cache/cacheLevel.js~CacheLevel.html#instance-method-_set",
    "lib/cache/cacheLevel.js~CacheLevel#_set",
    "method"
  ],
  [
    "lib/cache/cachelevel.js~cachelevel#constructor",
    "class/lib/cache/cacheLevel.js~CacheLevel.html#instance-constructor-constructor",
    "lib/cache/cacheLevel.js~CacheLevel#constructor",
    "method"
  ],
  [
    "lib/cache/cachelevel.js~cachelevel#db",
    "class/lib/cache/cacheLevel.js~CacheLevel.html#instance-member-db",
    "lib/cache/cacheLevel.js~CacheLevel#db",
    "member"
  ],
  [
    "lib/cache/cachememory.js",
    "file/lib/cache/cacheMemory.js.html",
    "lib/cache/cacheMemory.js",
    "file"
  ],
  [
    "lib/cache/cachememory.js~cachememory#_del",
    "class/lib/cache/cacheMemory.js~CacheMemory.html#instance-method-_del",
    "lib/cache/cacheMemory.js~CacheMemory#_del",
    "method"
  ],
  [
    "lib/cache/cachememory.js~cachememory#_get",
    "class/lib/cache/cacheMemory.js~CacheMemory.html#instance-method-_get",
    "lib/cache/cacheMemory.js~CacheMemory#_get",
    "method"
  ],
  [
    "lib/cache/cachememory.js~cachememory#_getkeys",
    "class/lib/cache/cacheMemory.js~CacheMemory.html#instance-method-_getKeys",
    "lib/cache/cacheMemory.js~CacheMemory#_getKeys",
    "method"
  ],
  [
    "lib/cache/cachememory.js~cachememory#_set",
    "class/lib/cache/cacheMemory.js~CacheMemory.html#instance-method-_set",
    "lib/cache/cacheMemory.js~CacheMemory#_set",
    "method"
  ],
  [
    "lib/cache/cachememory.js~cachememory#cache",
    "class/lib/cache/cacheMemory.js~CacheMemory.html#instance-member-cache",
    "lib/cache/cacheMemory.js~CacheMemory#cache",
    "member"
  ],
  [
    "lib/cache/cachememory.js~cachememory#constructor",
    "class/lib/cache/cacheMemory.js~CacheMemory.html#instance-constructor-constructor",
    "lib/cache/cacheMemory.js~CacheMemory#constructor",
    "method"
  ],
  [
    "lib/cache/scopedcache.js",
    "file/lib/cache/scopedCache.js.html",
    "lib/cache/scopedCache.js",
    "file"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#_initcache",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-_initCache",
    "lib/cache/scopedCache.js~ScopedCache#_initCache",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#_initcachepromise",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-member-_initCachePromise",
    "lib/cache/scopedCache.js~ScopedCache#_initCachePromise",
    "member"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#cache",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-member-cache",
    "lib/cache/scopedCache.js~ScopedCache#cache",
    "member"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#constructor",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-constructor-constructor",
    "lib/cache/scopedCache.js~ScopedCache#constructor",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#generatescopedkey",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-generateScopedKey",
    "lib/cache/scopedCache.js~ScopedCache#generateScopedKey",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#get",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-get",
    "lib/cache/scopedCache.js~ScopedCache#get",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#getglobal",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-getGlobal",
    "lib/cache/scopedCache.js~ScopedCache#getGlobal",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#initcache",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-initCache",
    "lib/cache/scopedCache.js~ScopedCache#initCache",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#prefix",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-member-prefix",
    "lib/cache/scopedCache.js~ScopedCache#prefix",
    "member"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#set",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-set",
    "lib/cache/scopedCache.js~ScopedCache#set",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#setglobal",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-setGlobal",
    "lib/cache/scopedCache.js~ScopedCache#setGlobal",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#version",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-member-version",
    "lib/cache/scopedCache.js~ScopedCache#version",
    "member"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#wrap",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-wrap",
    "lib/cache/scopedCache.js~ScopedCache#wrap",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#wrapglobal",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-wrapGlobal",
    "lib/cache/scopedCache.js~ScopedCache#wrapGlobal",
    "method"
  ],
  [
    "lib/configbase.js",
    "file/lib/configBase.js.html",
    "lib/configBase.js",
    "file"
  ],
  [
    "lib/configbase.js~configbase#config",
    "class/lib/configBase.js~ConfigBase.html#instance-member-config",
    "lib/configBase.js~ConfigBase#config",
    "member"
  ],
  [
    "lib/configbase.js~configbase#constructor",
    "class/lib/configBase.js~ConfigBase.html#instance-constructor-constructor",
    "lib/configBase.js~ConfigBase#constructor",
    "method"
  ],
  [
    "lib/index.js",
    "file/lib/index.js.html",
    "lib/index.js",
    "file"
  ],
  [
    "lib/parks/database.js",
    "file/lib/parks/database.js.html",
    "lib/parks/database.js",
    "file"
  ],
  [
    "lib/parks/database.js~database#_getentities",
    "class/lib/parks/database.js~Database.html#instance-method-_getEntities",
    "lib/parks/database.js~Database#_getEntities",
    "method"
  ],
  [
    "lib/parks/database.js~database#_init",
    "class/lib/parks/database.js~Database.html#instance-method-_init",
    "lib/parks/database.js~Database#_init",
    "method"
  ],
  [
    "lib/parks/database.js~database#cache",
    "class/lib/parks/database.js~Database.html#instance-member-cache",
    "lib/parks/database.js~Database#cache",
    "member"
  ],
  [
    "lib/parks/database.js~database#constructor",
    "class/lib/parks/database.js~Database.html#instance-constructor-constructor",
    "lib/parks/database.js~Database#constructor",
    "method"
  ],
  [
    "lib/parks/database.js~database#findentity",
    "class/lib/parks/database.js~Database.html#instance-method-findEntity",
    "lib/parks/database.js~Database#findEntity",
    "method"
  ],
  [
    "lib/parks/database.js~database#getentities",
    "class/lib/parks/database.js~Database.html#instance-method-getEntities",
    "lib/parks/database.js~Database#getEntities",
    "method"
  ],
  [
    "lib/parks/database.js~database#getentitiybyid",
    "class/lib/parks/database.js~Database.html#instance-method-getEntitiyById",
    "lib/parks/database.js~Database#getEntitiyById",
    "method"
  ],
  [
    "lib/parks/database.js~database#http",
    "class/lib/parks/database.js~Database.html#instance-member-http",
    "lib/parks/database.js~Database#http",
    "member"
  ],
  [
    "lib/parks/database.js~database#init",
    "class/lib/parks/database.js~Database.html#instance-method-init",
    "lib/parks/database.js~Database#init",
    "method"
  ],
  [
    "lib/parks/database.js~database.get",
    "class/lib/parks/database.js~Database.html#static-method-get",
    "lib/parks/database.js~Database.get",
    "method"
  ],
  [
    "lib/parks/dlp/disneylandparis.js",
    "file/lib/parks/dlp/disneylandparis.js.html",
    "lib/parks/dlp/disneylandparis.js",
    "file"
  ],
  [
    "lib/parks/dlp/disneylandparis.js~disneylandparismagickingdom#constructor",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisMagicKingdom.html#instance-constructor-constructor",
    "lib/parks/dlp/disneylandparis.js~DisneylandParisMagicKingdom#constructor",
    "method"
  ],
  [
    "lib/parks/dlp/disneylandparis.js~disneylandparispark#_buildattractionobject",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisPark.html#instance-method-_buildAttractionObject",
    "lib/parks/dlp/disneylandparis.js~DisneylandParisPark#_buildAttractionObject",
    "method"
  ],
  [
    "lib/parks/dlp/disneylandparis.js~disneylandparispark#_getoperatinghoursfordate",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisPark.html#instance-method-_getOperatingHoursForDate",
    "lib/parks/dlp/disneylandparis.js~DisneylandParisPark#_getOperatingHoursForDate",
    "method"
  ],
  [
    "lib/parks/dlp/disneylandparis.js~disneylandparispark#_init",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisPark.html#instance-method-_init",
    "lib/parks/dlp/disneylandparis.js~DisneylandParisPark#_init",
    "method"
  ],
  [
    "lib/parks/dlp/disneylandparis.js~disneylandparispark#_update",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisPark.html#instance-method-_update",
    "lib/parks/dlp/disneylandparis.js~DisneylandParisPark#_update",
    "method"
  ],
  [
    "lib/parks/dlp/disneylandparis.js~disneylandparispark#constructor",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisPark.html#instance-constructor-constructor",
    "lib/parks/dlp/disneylandparis.js~DisneylandParisPark#constructor",
    "method"
  ],
  [
    "lib/parks/dlp/disneylandparis.js~disneylandparispark#getparkdata",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisPark.html#instance-method-getParkData",
    "lib/parks/dlp/disneylandparis.js~DisneylandParisPark#getParkData",
    "method"
  ],
  [
    "lib/parks/dlp/disneylandparis.js~disneylandparispark#shutdown",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisPark.html#instance-method-shutdown",
    "lib/parks/dlp/disneylandparis.js~DisneylandParisPark#shutdown",
    "method"
  ],
  [
    "lib/parks/dlp/disneylandparis.js~disneylandparispark#waitapierrorcount",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisPark.html#instance-member-waitApiErrorCount",
    "lib/parks/dlp/disneylandparis.js~DisneylandParisPark#waitApiErrorCount",
    "member"
  ],
  [
    "lib/parks/dlp/disneylandparis.js~disneylandpariswaltdisneystudios#constructor",
    "class/lib/parks/dlp/disneylandparis.js~DisneylandParisWaltDisneyStudios.html#instance-constructor-constructor",
    "lib/parks/dlp/disneylandparis.js~DisneylandParisWaltDisneyStudios#constructor",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js",
    "file/lib/parks/efteling/efteling.js.html",
    "lib/parks/efteling/efteling.js",
    "file"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#_buildattractionobject",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-_buildAttractionObject",
    "lib/parks/efteling/efteling.js~Efteling#_buildAttractionObject",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#_getoperatinghoursfordate",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-_getOperatingHoursForDate",
    "lib/parks/efteling/efteling.js~Efteling#_getOperatingHoursForDate",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#_init",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-_init",
    "lib/parks/efteling/efteling.js~Efteling#_init",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#_update",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-_update",
    "lib/parks/efteling/efteling.js~Efteling#_update",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#constructor",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-constructor-constructor",
    "lib/parks/efteling/efteling.js~Efteling#constructor",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#getcalendarmonth",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-getCalendarMonth",
    "lib/parks/efteling/efteling.js~Efteling#getCalendarMonth",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#getpoidata",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-getPOIData",
    "lib/parks/efteling/efteling.js~Efteling#getPOIData",
    "method"
  ],
  [
    "lib/parks/entity.js",
    "file/lib/parks/entity.js.html",
    "lib/parks/entity.js",
    "file"
  ],
  [
    "lib/parks/entity.js~entity#[functionname]",
    "class/lib/parks/entity.js~Entity.html#instance-member-[functionName]",
    "lib/parks/entity.js~Entity#[functionName]",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#_hasofflinedata",
    "class/lib/parks/entity.js~Entity.html#instance-member-_hasOfflineData",
    "lib/parks/entity.js~Entity#_hasOfflineData",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#_offlinedata",
    "class/lib/parks/entity.js~Entity.html#instance-member-_offlineData",
    "lib/parks/entity.js~Entity#_offlineData",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#_offlinefunctions",
    "class/lib/parks/entity.js~Entity.html#instance-member-_offlineFunctions",
    "lib/parks/entity.js~Entity#_offlineFunctions",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#_offlinepromise",
    "class/lib/parks/entity.js~Entity.html#instance-member-_offlinePromise",
    "lib/parks/entity.js~Entity#_offlinePromise",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#_offlinepromiseresolve",
    "class/lib/parks/entity.js~Entity.html#instance-member-_offlinePromiseResolve",
    "lib/parks/entity.js~Entity#_offlinePromiseResolve",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#_postofflineload",
    "class/lib/parks/entity.js~Entity.html#instance-method-_postOfflineLoad",
    "lib/parks/entity.js~Entity#_postOfflineLoad",
    "method"
  ],
  [
    "lib/parks/entity.js~entity#constructor",
    "class/lib/parks/entity.js~Entity.html#instance-constructor-constructor",
    "lib/parks/entity.js~Entity#constructor",
    "method"
  ],
  [
    "lib/parks/entity.js~entity#ensurehasofflinedata",
    "class/lib/parks/entity.js~Entity.html#instance-method-ensureHasOfflineData",
    "lib/parks/entity.js~Entity#ensureHasOfflineData",
    "method"
  ],
  [
    "lib/parks/entity.js~entity#gettimenow",
    "class/lib/parks/entity.js~Entity.html#instance-method-getTimeNow",
    "lib/parks/entity.js~Entity#getTimeNow",
    "method"
  ],
  [
    "lib/parks/entity.js~entity#gettimenowmoment",
    "class/lib/parks/entity.js~Entity.html#instance-method-getTimeNowMoment",
    "lib/parks/entity.js~Entity#getTimeNowMoment",
    "method"
  ],
  [
    "lib/parks/entity.js~entity#getuniqueid",
    "class/lib/parks/entity.js~Entity.html#instance-method-getUniqueID",
    "lib/parks/entity.js~Entity#getUniqueID",
    "method"
  ],
  [
    "lib/parks/entity.js~entity#http",
    "class/lib/parks/entity.js~Entity.html#instance-member-http",
    "lib/parks/entity.js~Entity#http",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#injectfordomain",
    "class/lib/parks/entity.js~Entity.html#instance-method-injectForDomain",
    "lib/parks/entity.js~Entity#injectForDomain",
    "method"
  ],
  [
    "lib/parks/entity.js~entity#name",
    "class/lib/parks/entity.js~Entity.html#instance-get-name",
    "lib/parks/entity.js~Entity#name",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#offline",
    "class/lib/parks/entity.js~Entity.html#instance-get-offline",
    "lib/parks/entity.js~Entity#offline",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#registerofflinefunction",
    "class/lib/parks/entity.js~Entity.html#instance-method-registerOfflineFunction",
    "lib/parks/entity.js~Entity#registerOfflineFunction",
    "method"
  ],
  [
    "lib/parks/entity.js~entity#serialise",
    "class/lib/parks/entity.js~Entity.html#instance-method-serialise",
    "lib/parks/entity.js~Entity#serialise",
    "method"
  ],
  [
    "lib/parks/europa/europapark.js",
    "file/lib/parks/europa/europapark.js.html",
    "lib/parks/europa/europapark.js",
    "file"
  ],
  [
    "lib/parks/europa/europapark.js~europapark#constructor",
    "class/lib/parks/europa/europapark.js~EuropaPark.html#instance-constructor-constructor",
    "lib/parks/europa/europapark.js~EuropaPark#constructor",
    "method"
  ],
  [
    "lib/parks/europa/europapark.js~europaparkbase#_buildattractionobject",
    "class/lib/parks/europa/europapark.js~EuropaParkBase.html#instance-method-_buildAttractionObject",
    "lib/parks/europa/europapark.js~EuropaParkBase#_buildAttractionObject",
    "method"
  ],
  [
    "lib/parks/europa/europapark.js~europaparkbase#_getoperatinghoursfordate",
    "class/lib/parks/europa/europapark.js~EuropaParkBase.html#instance-method-_getOperatingHoursForDate",
    "lib/parks/europa/europapark.js~EuropaParkBase#_getOperatingHoursForDate",
    "method"
  ],
  [
    "lib/parks/europa/europapark.js~europaparkbase#_init",
    "class/lib/parks/europa/europapark.js~EuropaParkBase.html#instance-method-_init",
    "lib/parks/europa/europapark.js~EuropaParkBase#_init",
    "method"
  ],
  [
    "lib/parks/europa/europapark.js~europaparkbase#_update",
    "class/lib/parks/europa/europapark.js~EuropaParkBase.html#instance-method-_update",
    "lib/parks/europa/europapark.js~EuropaParkBase#_update",
    "method"
  ],
  [
    "lib/parks/europa/europapark.js~europaparkbase#constructor",
    "class/lib/parks/europa/europapark.js~EuropaParkBase.html#instance-constructor-constructor",
    "lib/parks/europa/europapark.js~EuropaParkBase#constructor",
    "method"
  ],
  [
    "lib/parks/europa/europapark.js~europaparkbase#db",
    "class/lib/parks/europa/europapark.js~EuropaParkBase.html#instance-get-db",
    "lib/parks/europa/europapark.js~EuropaParkBase#db",
    "member"
  ],
  [
    "lib/parks/europa/europapark.js~rulantica#constructor",
    "class/lib/parks/europa/europapark.js~Rulantica.html#instance-constructor-constructor",
    "lib/parks/europa/europapark.js~Rulantica#constructor",
    "method"
  ],
  [
    "lib/parks/europa/europapark.js~yullbe#constructor",
    "class/lib/parks/europa/europapark.js~Yullbe.html#instance-constructor-constructor",
    "lib/parks/europa/europapark.js~Yullbe#constructor",
    "method"
  ],
  [
    "lib/parks/europa/europaparkdb.js",
    "file/lib/parks/europa/europaparkdb.js.html",
    "lib/parks/europa/europaparkdb.js",
    "file"
  ],
  [
    "lib/parks/europa/europaparkdb.js~databaseeuropapark#_getentities",
    "class/lib/parks/europa/europaparkdb.js~DatabaseEuropaPark.html#instance-method-_getEntities",
    "lib/parks/europa/europaparkdb.js~DatabaseEuropaPark#_getEntities",
    "method"
  ],
  [
    "lib/parks/europa/europaparkdb.js~databaseeuropapark#_init",
    "class/lib/parks/europa/europaparkdb.js~DatabaseEuropaPark.html#instance-method-_init",
    "lib/parks/europa/europaparkdb.js~DatabaseEuropaPark#_init",
    "method"
  ],
  [
    "lib/parks/europa/europaparkdb.js~databaseeuropapark#bf",
    "class/lib/parks/europa/europaparkdb.js~DatabaseEuropaPark.html#instance-member-bf",
    "lib/parks/europa/europaparkdb.js~DatabaseEuropaPark#bf",
    "member"
  ],
  [
    "lib/parks/europa/europaparkdb.js~databaseeuropapark#constructor",
    "class/lib/parks/europa/europaparkdb.js~DatabaseEuropaPark.html#instance-constructor-constructor",
    "lib/parks/europa/europaparkdb.js~DatabaseEuropaPark#constructor",
    "method"
  ],
  [
    "lib/parks/europa/europaparkdb.js~databaseeuropapark#getcalendar",
    "class/lib/parks/europa/europaparkdb.js~DatabaseEuropaPark.html#instance-method-getCalendar",
    "lib/parks/europa/europaparkdb.js~DatabaseEuropaPark#getCalendar",
    "method"
  ],
  [
    "lib/parks/europa/europaparkdb.js~databaseeuropapark#getconfig",
    "class/lib/parks/europa/europaparkdb.js~DatabaseEuropaPark.html#instance-method-getConfig",
    "lib/parks/europa/europaparkdb.js~DatabaseEuropaPark#getConfig",
    "method"
  ],
  [
    "lib/parks/europa/europaparkdb.js~databaseeuropapark#getfirebaseid",
    "class/lib/parks/europa/europaparkdb.js~DatabaseEuropaPark.html#instance-method-getFirebaseID",
    "lib/parks/europa/europaparkdb.js~DatabaseEuropaPark#getFirebaseID",
    "method"
  ],
  [
    "lib/parks/europa/europaparkdb.js~databaseeuropapark#getparkdata",
    "class/lib/parks/europa/europaparkdb.js~DatabaseEuropaPark.html#instance-method-getParkData",
    "lib/parks/europa/europaparkdb.js~DatabaseEuropaPark#getParkData",
    "method"
  ],
  [
    "lib/parks/europa/europaparkdb.js~databaseeuropapark#gettoken",
    "class/lib/parks/europa/europaparkdb.js~DatabaseEuropaPark.html#instance-method-getToken",
    "lib/parks/europa/europaparkdb.js~DatabaseEuropaPark#getToken",
    "method"
  ],
  [
    "lib/parks/europa/europaparkdb.js~databaseeuropapark#getwaitingtimes",
    "class/lib/parks/europa/europaparkdb.js~DatabaseEuropaPark.html#instance-method-getWaitingTimes",
    "lib/parks/europa/europaparkdb.js~DatabaseEuropaPark#getWaitingTimes",
    "method"
  ],
  [
    "lib/parks/http.js",
    "file/lib/parks/http.js.html",
    "lib/parks/http.js",
    "file"
  ],
  [
    "lib/parks/park.js",
    "file/lib/parks/park.js.html",
    "lib/parks/park.js",
    "file"
  ],
  [
    "lib/parks/park.js~park#_attractions",
    "class/lib/parks/park.js~Park.html#instance-member-_attractions",
    "lib/parks/park.js~Park#_attractions",
    "member"
  ],
  [
    "lib/parks/park.js~park#_buildattractionobject",
    "class/lib/parks/park.js~Park.html#instance-method-_buildAttractionObject",
    "lib/parks/park.js~Park#_buildAttractionObject",
    "method"
  ],
  [
    "lib/parks/park.js~park#_checkdate",
    "class/lib/parks/park.js~Park.html#instance-method-_checkDate",
    "lib/parks/park.js~Park#_checkDate",
    "method"
  ],
  [
    "lib/parks/park.js~park#_currentdate",
    "class/lib/parks/park.js~Park.html#instance-member-_currentDate",
    "lib/parks/park.js~Park#_currentDate",
    "member"
  ],
  [
    "lib/parks/park.js~park#_daterefresh",
    "class/lib/parks/park.js~Park.html#instance-method-_dateRefresh",
    "lib/parks/park.js~Park#_dateRefresh",
    "method"
  ],
  [
    "lib/parks/park.js~park#_findattractionbyid",
    "class/lib/parks/park.js~Park.html#instance-method-_findAttractionByID",
    "lib/parks/park.js~Park#_findAttractionByID",
    "method"
  ],
  [
    "lib/parks/park.js~park#_getattractionbyidinternal",
    "class/lib/parks/park.js~Park.html#instance-method-_getAttractionByIDInternal",
    "lib/parks/park.js~Park#_getAttractionByIDInternal",
    "method"
  ],
  [
    "lib/parks/park.js~park#_getoperatinghoursfordate",
    "class/lib/parks/park.js~Park.html#instance-method-_getOperatingHoursForDate",
    "lib/parks/park.js~Park#_getOperatingHoursForDate",
    "method"
  ],
  [
    "lib/parks/park.js~park#_init",
    "class/lib/parks/park.js~Park.html#instance-method-_init",
    "lib/parks/park.js~Park#_init",
    "method"
  ],
  [
    "lib/parks/park.js~park#_pendingtags",
    "class/lib/parks/park.js~Park.html#instance-member-_pendingTags",
    "lib/parks/park.js~Park#_pendingTags",
    "member"
  ],
  [
    "lib/parks/park.js~park#_postofflineload",
    "class/lib/parks/park.js~Park.html#instance-method-_postOfflineLoad",
    "lib/parks/park.js~Park#_postOfflineLoad",
    "method"
  ],
  [
    "lib/parks/park.js~park#_runinit",
    "class/lib/parks/park.js~Park.html#instance-method-_runInit",
    "lib/parks/park.js~Park#_runInit",
    "method"
  ],
  [
    "lib/parks/park.js~park#_runupdate",
    "class/lib/parks/park.js~Park.html#instance-method-_runUpdate",
    "lib/parks/park.js~Park#_runUpdate",
    "method"
  ],
  [
    "lib/parks/park.js~park#_update",
    "class/lib/parks/park.js~Park.html#instance-method-_update",
    "lib/parks/park.js~Park#_update",
    "method"
  ],
  [
    "lib/parks/park.js~park#cache",
    "class/lib/parks/park.js~Park.html#instance-member-cache",
    "lib/parks/park.js~Park#cache",
    "member"
  ],
  [
    "lib/parks/park.js~park#cacheattractionobject",
    "class/lib/parks/park.js~Park.html#instance-method-cacheAttractionObject",
    "lib/parks/park.js~Park#cacheAttractionObject",
    "method"
  ],
  [
    "lib/parks/park.js~park#constructor",
    "class/lib/parks/park.js~Park.html#instance-constructor-constructor",
    "lib/parks/park.js~Park#constructor",
    "method"
  ],
  [
    "lib/parks/park.js~park#ensureready",
    "class/lib/parks/park.js~Park.html#instance-method-ensureReady",
    "lib/parks/park.js~Park#ensureReady",
    "method"
  ],
  [
    "lib/parks/park.js~park#findattractionbyid",
    "class/lib/parks/park.js~Park.html#instance-method-findAttractionByID",
    "lib/parks/park.js~Park#findAttractionByID",
    "method"
  ],
  [
    "lib/parks/park.js~park#getactiveparkdate",
    "class/lib/parks/park.js~Park.html#instance-method-getActiveParkDate",
    "lib/parks/park.js~Park#getActiveParkDate",
    "method"
  ],
  [
    "lib/parks/park.js~park#getactiveparkdatemoment",
    "class/lib/parks/park.js~Park.html#instance-method-getActiveParkDateMoment",
    "lib/parks/park.js~Park#getActiveParkDateMoment",
    "method"
  ],
  [
    "lib/parks/park.js~park#getattractions",
    "class/lib/parks/park.js~Park.html#instance-method-getAttractions",
    "lib/parks/park.js~Park#getAttractions",
    "method"
  ],
  [
    "lib/parks/park.js~park#getcalendar",
    "class/lib/parks/park.js~Park.html#instance-method-getCalendar",
    "lib/parks/park.js~Park#getCalendar",
    "method"
  ],
  [
    "lib/parks/park.js~park#getcalendarfortoday",
    "class/lib/parks/park.js~Park.html#instance-method-getCalendarForToday",
    "lib/parks/park.js~Park#getCalendarForToday",
    "method"
  ],
  [
    "lib/parks/park.js~park#getcalendarfortomorrow",
    "class/lib/parks/park.js~Park.html#instance-method-getCalendarForTomorrow",
    "lib/parks/park.js~Park#getCalendarForTomorrow",
    "method"
  ],
  [
    "lib/parks/park.js~park#getnextclosingtime",
    "class/lib/parks/park.js~Park.html#instance-method-getNextClosingTime",
    "lib/parks/park.js~Park#getNextClosingTime",
    "method"
  ],
  [
    "lib/parks/park.js~park#getnextopeningtime",
    "class/lib/parks/park.js~Park.html#instance-method-getNextOpeningTime",
    "lib/parks/park.js~Park#getNextOpeningTime",
    "method"
  ],
  [
    "lib/parks/park.js~park#getnextopeningtimemomentduration",
    "class/lib/parks/park.js~Park.html#instance-method-getNextOpeningTimeMomentDuration",
    "lib/parks/park.js~Park#getNextOpeningTimeMomentDuration",
    "method"
  ],
  [
    "lib/parks/park.js~park#getoperatinghoursfordate",
    "class/lib/parks/park.js~Park.html#instance-method-getOperatingHoursForDate",
    "lib/parks/park.js~Park#getOperatingHoursForDate",
    "method"
  ],
  [
    "lib/parks/park.js~park#getparkuniqueid",
    "class/lib/parks/park.js~Park.html#instance-method-getParkUniqueID",
    "lib/parks/park.js~Park#getParkUniqueID",
    "method"
  ],
  [
    "lib/parks/park.js~park#hasrunupdate",
    "class/lib/parks/park.js~Park.html#instance-member-hasRunUpdate",
    "lib/parks/park.js~Park#hasRunUpdate",
    "member"
  ],
  [
    "lib/parks/park.js~park#init",
    "class/lib/parks/park.js~Park.html#instance-method-init",
    "lib/parks/park.js~Park#init",
    "method"
  ],
  [
    "lib/parks/park.js~park#initialised",
    "class/lib/parks/park.js~Park.html#instance-member-initialised",
    "lib/parks/park.js~Park#initialised",
    "member"
  ],
  [
    "lib/parks/park.js~park#postupdate",
    "class/lib/parks/park.js~Park.html#instance-method-postUpdate",
    "lib/parks/park.js~Park#postUpdate",
    "method"
  ],
  [
    "lib/parks/park.js~park#removeattractiontag",
    "class/lib/parks/park.js~Park.html#instance-method-removeAttractionTag",
    "lib/parks/park.js~Park#removeAttractionTag",
    "method"
  ],
  [
    "lib/parks/park.js~park#setattractiontag",
    "class/lib/parks/park.js~Park.html#instance-method-setAttractionTag",
    "lib/parks/park.js~Park#setAttractionTag",
    "method"
  ],
  [
    "lib/parks/park.js~park#shutdown",
    "class/lib/parks/park.js~Park.html#instance-method-shutdown",
    "lib/parks/park.js~Park#shutdown",
    "method"
  ],
  [
    "lib/parks/park.js~park#toggleattractiontag",
    "class/lib/parks/park.js~Park.html#instance-method-toggleAttractionTag",
    "lib/parks/park.js~Park#toggleAttractionTag",
    "method"
  ],
  [
    "lib/parks/park.js~park#update",
    "class/lib/parks/park.js~Park.html#instance-method-update",
    "lib/parks/park.js~Park#update",
    "method"
  ],
  [
    "lib/parks/park.js~park#updateattractionqueue",
    "class/lib/parks/park.js~Park.html#instance-method-updateAttractionQueue",
    "lib/parks/park.js~Park#updateAttractionQueue",
    "method"
  ],
  [
    "lib/parks/park.js~park#updateattractionstate",
    "class/lib/parks/park.js~Park.html#instance-method-updateAttractionState",
    "lib/parks/park.js~Park#updateAttractionState",
    "method"
  ],
  [
    "lib/parks/parktypes.js",
    "file/lib/parks/parkTypes.js.html",
    "lib/parks/parkTypes.js",
    "file"
  ],
  [
    "lib/parks/resort.js",
    "file/lib/parks/resort.js.html",
    "lib/parks/resort.js",
    "file"
  ],
  [
    "lib/parks/resort.js~resort#_newparkoptions",
    "class/lib/parks/resort.js~Resort.html#instance-member-_newParkOptions",
    "lib/parks/resort.js~Resort#_newParkOptions",
    "member"
  ],
  [
    "lib/parks/resort.js~resort#_parks",
    "class/lib/parks/resort.js~Resort.html#instance-member-_parks",
    "lib/parks/resort.js~Resort#_parks",
    "member"
  ],
  [
    "lib/parks/resort.js~resort#addpark",
    "class/lib/parks/resort.js~Resort.html#instance-method-addPark",
    "lib/parks/resort.js~Resort#addPark",
    "method"
  ],
  [
    "lib/parks/resort.js~resort#addparkclass",
    "class/lib/parks/resort.js~Resort.html#instance-method-addParkClass",
    "lib/parks/resort.js~Resort#addParkClass",
    "method"
  ],
  [
    "lib/parks/resort.js~resort#constructor",
    "class/lib/parks/resort.js~Resort.html#instance-constructor-constructor",
    "lib/parks/resort.js~Resort#constructor",
    "method"
  ],
  [
    "lib/parks/resort.js~resort#getparks",
    "class/lib/parks/resort.js~Resort.html#instance-method-getParks",
    "lib/parks/resort.js~Resort#getParks",
    "method"
  ],
  [
    "lib/parks/sieve.js",
    "file/lib/parks/sieve.js.html",
    "lib/parks/sieve.js",
    "file"
  ],
  [
    "lib/parks/tags.js",
    "file/lib/parks/tags.js.html",
    "lib/parks/tags.js",
    "file"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js",
    "file/lib/parks/tdr/tokyodisneyresort.js.html",
    "lib/parks/tdr/tokyodisneyresort.js",
    "file"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js~tokyodisneyresortpark#_buildattractionobject",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark.html#instance-method-_buildAttractionObject",
    "lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark#_buildAttractionObject",
    "method"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js~tokyodisneyresortpark#_getoperatinghoursfordate",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark.html#instance-method-_getOperatingHoursForDate",
    "lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark#_getOperatingHoursForDate",
    "method"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js~tokyodisneyresortpark#_init",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark.html#instance-method-_init",
    "lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark#_init",
    "method"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js~tokyodisneyresortpark#_update",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark.html#instance-method-_update",
    "lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark#_update",
    "method"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js~tokyodisneyresortpark#constructor",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark.html#instance-constructor-constructor",
    "lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark#constructor",
    "method"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js~tokyodisneyresortpark#fetchallfacilitiesdata",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark.html#instance-method-fetchAllFacilitiesData",
    "lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark#fetchAllFacilitiesData",
    "method"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js~tokyodisneyresortpark#fetchcalendar",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark.html#instance-method-fetchCalendar",
    "lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark#fetchCalendar",
    "method"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js~tokyodisneyresortpark#fetchdeviceid",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark.html#instance-method-fetchDeviceID",
    "lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark#fetchDeviceID",
    "method"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js~tokyodisneyresortpark#fetchfacilitiesdata",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark.html#instance-method-fetchFacilitiesData",
    "lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark#fetchFacilitiesData",
    "method"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js~tokyodisneyresortpark#fetchlatestversion",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark.html#instance-method-fetchLatestVersion",
    "lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyResortPark#fetchLatestVersion",
    "method"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js~tokyodisneysea#constructor",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneySea.html#instance-constructor-constructor",
    "lib/parks/tdr/tokyodisneyresort.js~TokyoDisneySea#constructor",
    "method"
  ],
  [
    "lib/parks/tdr/tokyodisneyresort.js~tokyodisneyland#constructor",
    "class/lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyland.html#instance-constructor-constructor",
    "lib/parks/tdr/tokyodisneyresort.js~TokyoDisneyland#constructor",
    "method"
  ],
  [
    "lib/parks/types.js",
    "file/lib/parks/types.js.html",
    "lib/parks/types.js",
    "file"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js",
    "file/lib/parks/wdw/waltdisneyworldbase.js.html",
    "lib/parks/wdw/waltdisneyworldbase.js",
    "file"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~disneypark#_buildattractionobject",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneyPark.html#instance-method-_buildAttractionObject",
    "lib/parks/wdw/waltdisneyworldbase.js~DisneyPark#_buildAttractionObject",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~disneypark#_getoperatinghoursfordate",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneyPark.html#instance-method-_getOperatingHoursForDate",
    "lib/parks/wdw/waltdisneyworldbase.js~DisneyPark#_getOperatingHoursForDate",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~disneypark#_init",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneyPark.html#instance-method-_init",
    "lib/parks/wdw/waltdisneyworldbase.js~DisneyPark#_init",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~disneypark#_processattractionstatusupdate",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneyPark.html#instance-method-_processAttractionStatusUpdate",
    "lib/parks/wdw/waltdisneyworldbase.js~DisneyPark#_processAttractionStatusUpdate",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~disneypark#_update",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneyPark.html#instance-method-_update",
    "lib/parks/wdw/waltdisneyworldbase.js~DisneyPark#_update",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~disneypark#constructor",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneyPark.html#instance-constructor-constructor",
    "lib/parks/wdw/waltdisneyworldbase.js~DisneyPark#constructor",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~disneypark#db",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneyPark.html#instance-member-db",
    "lib/parks/wdw/waltdisneyworldbase.js~DisneyPark#db",
    "member"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~disneypark#getfacilitystatuschannelid",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneyPark.html#instance-method-getFacilityStatusChannelID",
    "lib/parks/wdw/waltdisneyworldbase.js~DisneyPark#getFacilityStatusChannelID",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~disneypark.getdatabase",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneyPark.html#static-method-getDatabase",
    "lib/parks/wdw/waltdisneyworldbase.js~DisneyPark.getDatabase",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~disneylandresortcaliforniaadventure#constructor",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneylandResortCaliforniaAdventure.html#instance-constructor-constructor",
    "lib/parks/wdw/waltdisneyworldbase.js~DisneylandResortCaliforniaAdventure#constructor",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~disneylandresortmagickingdom#constructor",
    "class/lib/parks/wdw/waltdisneyworldbase.js~DisneylandResortMagicKingdom.html#instance-constructor-constructor",
    "lib/parks/wdw/waltdisneyworldbase.js~DisneylandResortMagicKingdom#constructor",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~hongkongdisneylandpark#constructor",
    "class/lib/parks/wdw/waltdisneyworldbase.js~HongKongDisneylandPark.html#instance-constructor-constructor",
    "lib/parks/wdw/waltdisneyworldbase.js~HongKongDisneylandPark#constructor",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~waltdisneyworldanimalkingdom#constructor",
    "class/lib/parks/wdw/waltdisneyworldbase.js~WaltDisneyWorldAnimalKingdom.html#instance-constructor-constructor",
    "lib/parks/wdw/waltdisneyworldbase.js~WaltDisneyWorldAnimalKingdom#constructor",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~waltdisneyworldepcot#constructor",
    "class/lib/parks/wdw/waltdisneyworldbase.js~WaltDisneyWorldEpcot.html#instance-constructor-constructor",
    "lib/parks/wdw/waltdisneyworldbase.js~WaltDisneyWorldEpcot#constructor",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~waltdisneyworldhollywoodstudios#constructor",
    "class/lib/parks/wdw/waltdisneyworldbase.js~WaltDisneyWorldHollywoodStudios.html#instance-constructor-constructor",
    "lib/parks/wdw/waltdisneyworldbase.js~WaltDisneyWorldHollywoodStudios#constructor",
    "method"
  ],
  [
    "lib/parks/wdw/waltdisneyworldbase.js~waltdisneyworldmagickingdom#constructor",
    "class/lib/parks/wdw/waltdisneyworldbase.js~WaltDisneyWorldMagicKingdom.html#instance-constructor-constructor",
    "lib/parks/wdw/waltdisneyworldbase.js~WaltDisneyWorldMagicKingdom#constructor",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdatabase.js",
    "file/lib/parks/wdw/wdwdatabase.js.html",
    "lib/parks/wdw/wdwdatabase.js",
    "file"
  ],
  [
    "lib/parks/wdw/wdwdatabase.js~databasewdw#_getentities",
    "class/lib/parks/wdw/wdwdatabase.js~DatabaseWDW.html#instance-method-_getEntities",
    "lib/parks/wdw/wdwdatabase.js~DatabaseWDW#_getEntities",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdatabase.js~databasewdw#constructor",
    "class/lib/parks/wdw/wdwdatabase.js~DatabaseWDW.html#instance-constructor-constructor",
    "lib/parks/wdw/wdwdatabase.js~DatabaseWDW#constructor",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdatabase.js~databasewdw#db",
    "class/lib/parks/wdw/wdwdatabase.js~DatabaseWDW.html#instance-member-db",
    "lib/parks/wdw/wdwdatabase.js~DatabaseWDW#db",
    "member"
  ],
  [
    "lib/parks/wdw/wdwdb.js",
    "file/lib/parks/wdw/wdwdb.js.html",
    "lib/parks/wdw/wdwdb.js",
    "file"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#_createindex",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-_createIndex",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#_createIndex",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#_createindexes",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-_createIndexes",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#_createIndexes",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#_extractchannellanguage",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-_extractChannelLanguage",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#_extractChannelLanguage",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#_extractentitykeys",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-_extractEntityKeys",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#_extractEntityKeys",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#_index",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-member-_index",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#_index",
    "member"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#_indexsetup",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-member-_indexSetup",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#_indexSetup",
    "member"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#_indexwdwdocument",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-_indexWDWDocument",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#_indexWDWDocument",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#_initindexes",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-_initIndexes",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#_initIndexes",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#_loadandinit",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-_loadAndInit",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#_loadAndInit",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#_removefromarrayindex",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-_removeFromArrayIndex",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#_removeFromArrayIndex",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#_replicate",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-_replicate",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#_replicate",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#_setuppromise",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-member-_setupPromise",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#_setupPromise",
    "member"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#config",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-member-config",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#config",
    "member"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#constructor",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-constructor-constructor",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#constructor",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#databasedumppendingpromise",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-member-databaseDumpPendingPromise",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#databaseDumpPendingPromise",
    "member"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#find",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-find",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#find",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#getbychannel",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-getByChannel",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#getByChannel",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#getdocsbyid",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-getDocsById",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#getDocsById",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#getdumpfilename",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-getDumpFilename",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#getDumpFilename",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#getentity",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-getEntity",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#getEntity",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#getentityindex",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-getEntityIndex",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#getEntityIndex",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#getentityone",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-getEntityOne",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#getEntityOne",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#getfacilitystatus",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-getFacilityStatus",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#getFacilityStatus",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#getindex",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-getIndex",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#getIndex",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#init",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-init",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#init",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#initpromisesync",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-member-initPromiseSync",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#initPromiseSync",
    "member"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#loadsnapshot",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-loadSnapshot",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#loadSnapshot",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#remotedb",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-member-remoteDB",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#remoteDB",
    "member"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#replicating",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-member-replicating",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#replicating",
    "member"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#savesnapshot",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-saveSnapshot",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#saveSnapshot",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#subscribetochanges",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-subscribeToChanges",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#subscribeToChanges",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#subscribetochannel",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-method-subscribeToChannel",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#subscribeToChannel",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb#synced",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#instance-member-synced",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB#synced",
    "member"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb._pluginbulkdocs",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#static-method-_pluginBulkDocs",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB._pluginBulkDocs",
    "method"
  ],
  [
    "lib/parks/wdw/wdwdb.js~indexedwdwdb.getdatabasefilepath",
    "class/lib/parks/wdw/wdwdb.js~IndexedWDWDB.html#static-method-getDatabaseFilePath",
    "lib/parks/wdw/wdwdb.js~IndexedWDWDB.getDatabaseFilePath",
    "method"
  ],
  [
    "lib/reusepromises.js",
    "file/lib/reusePromises.js.html",
    "lib/reusePromises.js",
    "file"
  ]
]